[build]
  base = "frontend"
  publish = "frontend/dist"
  command = "npm run build"

[build.environment]
  VITE_SUPABASE_URL = "https://your-project-id.supabase.co"
  VITE_SUPABASE_ANON_KEY = "your-anon-key"
